# Generated by Django 2.0.4 on 2018-05-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryTechnologyAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_tech_area', models.CharField(choices=[('LPS', 'Launch Propulsion Systems'), ('ISPT', 'In-Space Propulsion Technologies'), ('SPES', 'Space Power and Energy Storage'), ('RAS', 'Robotics and Autonomous Systems'), ('CNODTCS', 'Communications, Navigation, and Orbital Debris Tracking and Characterization Systems'), ('HHLSHS', 'Human Health, Life Support, and Habitation Systems'), ('HEDS', 'Human Exploration Destination Systems'), ('SIOSS', 'Science Instruments, Observatories, and Sensor Systems'), ('EDLS', 'Entry, Descent, and Landing Systems'), ('N', 'Nanotechnology'), ('MSITP', 'Modeling, Simulation, Information Technology and Processing'), ('MSMSM', 'Materials, Structures, Mechanical Systems and Manufacturing'), ('GLS', 'Ground and Launch Systems'), ('TMS', 'Thermal Management Systems'), ('A', 'Aeronautics')], default='LPS', max_length=7)),
            ],
        ),
    ]
