# Generated by Django 2.0.4 on 2018-07-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsort', '0003_auto_20180701_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarytechnologyareas',
            name='choose_date',
        ),
    ]
