# Generated by Django 2.0.4 on 2018-07-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsort', '0004_remove_primarytechnologyareas_choose_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarytechnologyareas',
            name='pub_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
