# Generated by Django 2.0.4 on 2018-07-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsort', '0005_primarytechnologyareas_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrimaryTechnologyAreas',
            new_name='PrimaryTech',
        ),
    ]
